[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[project]
name = "sshame"
version = "0.12.beta"
dependencies = [
	'asyncssh >= 1.15.1',
	'cmd2 >= 0.10.0',
	'colorama',
	'sqlalchemy',
	'scapy',
	'tabulate',
	'pyyaml',
]
[project.scripts]
sshame = "sshame.main:main"
